# Generated by Django 4.0.4 on 2022-07-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=b'I01\n', null=b'I01\n', upload_to=''),
            preserve_default=b'I01\n',
        ),
    ]
